# Example Code generated by Beijing Volcanoengine Technology.
from __future__ import print_function
import volcenginesdkcore
import volcenginesdkbilling
from volcenginesdkcore.rest import ApiException
import configparser



def find_doubao_money():
    config = configparser.ConfigParser()
    config.read('config.ini')

    ak = config.get('doubao', 'ak')
    sk = config.get('doubao', 'sk')

    configuration = volcenginesdkcore.Configuration()
    configuration.ak = ak
    configuration.sk = sk
    configuration.region = "cn-beijing"
    volcenginesdkcore.Configuration.set_default(configuration)

    api_instance = volcenginesdkbilling.BILLINGApi()
    query_balance_acct_request = volcenginesdkbilling.QueryBalanceAcctRequest(
    )

    try:
        response = api_instance.query_balance_acct(query_balance_acct_request)
        return response
    except ApiException as e:
        return e
        pass
